[package]
name = "predicate"
version = "0.1.0"
authors = ["Alexander Klizhentas <klizhentas@gmail.com>"]
edition = "2018"

[[bin]]
name = "predicate"
path = "src/predicate/main.rs"

[lib]
crate-type =["cdylib"]

[dependencies]
crepe = "0.1.5"
sha1 = "0.6.0"
protobuf = "2.24.1"